/* This file was generated by mkint-h */

#define BCPLINT32 int
#define BCPLUINT32 unsigned int
#define BCPLINT64 long
#define BCPLUINT64 unsigned long
#define CURRENT64
#define ADDRINT BCPLINT64
#define FLOAT32 float
#define FLOAT64 double
#define BCPLCHAR signed char
#define UBCPLCHAR unsigned char
